package table;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.std.framework.core.db.table.Feed;
import com.std.framework.business.user.db.entity.User;

import table.FeedDao;
import table.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig feedDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FeedDao feedDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        feedDaoConfig = daoConfigMap.get(FeedDao.class).clone();
        feedDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        feedDao = new FeedDao(feedDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Feed.class, feedDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        feedDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FeedDao getFeedDao() {
        return feedDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
