package com.cn.sale.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "user".
 */
public class User implements java.io.Serializable {

    private String login_id;
    private String nick_name;
    /** Not-null value. */
    private String password;
    private String ticket;
    private String token;
    private String group_id;
    private String portrait;

    public User() {
    }

    public User(String login_id) {
        this.login_id = login_id;
    }

    public User(String login_id, String nick_name, String password, String ticket, String token, String group_id, String portrait) {
        this.login_id = login_id;
        this.nick_name = nick_name;
        this.password = password;
        this.ticket = ticket;
        this.token = token;
        this.group_id = group_id;
        this.portrait = portrait;
    }

    public String getLogin_id() {
        return login_id;
    }

    public void setLogin_id(String login_id) {
        this.login_id = login_id;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getTicket() {
        return ticket;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

}
