///  created by：sunyuancun
/// 2020/9/12
///desc:

const int MINE_BUY_LIST_PAGE_ALL_TAB = 0;
const int MINE_BUY_LIST_PAGE_WAIT_PAY_TAB = 1;
const int MINE_BUY_LIST_PAGE_WAIT_RECEIVING_TAB = 2;
const int MINE_BUY_LIST_PAGE_COMPLETED_TAB = 3;
const int MINE_BUY_LIST_PAGE_CANCEL_TAB = 4;

const int MINE_SELL_LIST_PAGE_ALL_TAB = 0;
const int MINE_SELL_LIST_PAGE_WAIT_GATHERING_TAB = 1;
const int MINE_SELL_LIST_PAGE_WAIT_REPLENISH_TAB = 2;
const int MINE_SELL_LIST_PAGE_COMPLETED_TAB = 3;

const int FORGET_LOGIN_PWD_PAGE_FROM_LOGIN_TYPE = 0;
const int FORGET_LOGIN_PWD_PAGE_FROM_PWD_MANAGER_TYPE = 1;
