/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.0.2-65-g938bc919ea"
#endif /* AVUTIL_FFVERSION_H */
